/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package acousticfield3d.gui.panels;

import acousticfield3d.gui.MainForm;
import acousticfield3d.simulation.FieldSource;
import acousticfield3d.simulation.PreCubeCalculator;
import acousticfield3d.utils.Parse;

/**
 *
 * @author Asier
 */
public class PreCubePanel extends javax.swing.JPanel {
    public MainForm mf;
    
    public float timeA=1, timeB=0;
    
    PreCubeCalculator worker;
    
    public PreCubePanel(MainForm mf) {
        this.mf = mf;
        
        worker = new PreCubeCalculator(this);
        worker.start();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel17 = new javax.swing.JLabel();
        cubeSizeText = new javax.swing.JTextField();
        okCubeButton = new javax.swing.JButton();
        cubeSourceAmpCheck = new javax.swing.JRadioButton();
        cubeSourcePhaseCheck = new javax.swing.JRadioButton();
        cubeProgress = new javax.swing.JProgressBar();
        nAmpRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        nAmpText = new javax.swing.JTextField();

        jLabel17.setText("Size:");

        cubeSizeText.setText("128");

        okCubeButton.setText("OK");
        okCubeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCubeButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(cubeSourceAmpCheck);
        cubeSourceAmpCheck.setSelected(true);
        cubeSourceAmpCheck.setText("Amp");
        cubeSourceAmpCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeSourceAmpCheckActionPerformed(evt);
            }
        });

        buttonGroup1.add(cubeSourcePhaseCheck);
        cubeSourcePhaseCheck.setText("Phase");
        cubeSourcePhaseCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeSourcePhaseCheckActionPerformed(evt);
            }
        });

        buttonGroup1.add(nAmpRadio);
        nAmpRadio.setText("NAmp");

        jLabel1.setText("MaxNAmp:");

        nAmpText.setText("10000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cubeProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cubeSizeText)
                        .addGap(18, 18, 18)
                        .addComponent(okCubeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cubeSourceAmpCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cubeSourcePhaseCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nAmpRadio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nAmpText)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cubeSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okCubeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cubeSourceAmpCheck)
                    .addComponent(cubeSourcePhaseCheck)
                    .addComponent(nAmpRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nAmpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cubeProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public PreCubeCalculator getWorker() {
        return worker;
    }

    
    private void okCubeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCubeButtonActionPerformed
        worker.update();
    }//GEN-LAST:event_okCubeButtonActionPerformed

    private void cubeSourceAmpCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeSourceAmpCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cubeSourceAmpCheckActionPerformed

    private void cubeSourcePhaseCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeSourcePhaseCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cubeSourcePhaseCheckActionPerformed

    public boolean isAmpSelected(){
        return cubeSourceAmpCheck.isSelected();
    }
    
    public int getPreCubeSize() {
        return Parse.stringToInt(cubeSizeText.getText() );
    }

    public void updatePreCalcProgress(int p) {
        cubeProgress.setValue( p );
    }

    public FieldSource getPreCubeSource() {
        if (cubeSourceAmpCheck.isSelected()) { return FieldSource.sourceAmp; }
        else if (cubeSourcePhaseCheck.isSelected()) { return FieldSource.sourcePhase; }
        else if (nAmpRadio.isSelected()) { return FieldSource.sourceNegativeAmp; }
        
        return FieldSource.sourceAmp;
    }
    
    public float getNegativeAmp(){
        return Parse.stringToFloat( nAmpText.getText() );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JProgressBar cubeProgress;
    private javax.swing.JTextField cubeSizeText;
    private javax.swing.JRadioButton cubeSourceAmpCheck;
    private javax.swing.JRadioButton cubeSourcePhaseCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JRadioButton nAmpRadio;
    private javax.swing.JTextField nAmpText;
    private javax.swing.JButton okCubeButton;
    // End of variables declaration//GEN-END:variables
}
