/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package acousticfield3d.gui.panels;

import acousticfield3d.gui.MainForm;
import acousticfield3d.gui.controls.SliderPanel;
import acousticfield3d.renderer.MarchingCubes;
import acousticfield3d.simulation.IsoSurface;
import acousticfield3d.utils.FileUtils;
import acousticfield3d.utils.GenericListModel;
import acousticfield3d.utils.Parse;
import java.awt.event.ActionListener;

/**
 *
 * @author Asier
 */
public class PreIsoPanel extends javax.swing.JPanel {
    public MainForm mf;
    
    SliderPanel rtIsoSliderPanel;
    GenericListModel<IsoSurface> isoSurfaces;
    
    public PreIsoPanel(MainForm mf) {
        this.mf = mf;
        rtIsoSliderPanel = new SliderPanel(1, false);
        isoSurfaces = new GenericListModel<>();
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        preIsoAlphaText = new javax.swing.JTextField();
        preIsoAddButton = new javax.swing.JButton();
        preIsoProgress = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        preIsoList = new javax.swing.JList();
        preIsoShowButton = new javax.swing.JButton();
        preIsoHideButton = new javax.swing.JButton();
        preIsoDelButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        preIsoSteps = new javax.swing.JTextField();
        setPreIsoButton = new javax.swing.JButton();
        saveIsoButton = new javax.swing.JButton();
        minRTIsoText = new javax.swing.JTextField();
        maxRTIsoText = new javax.swing.JTextField();
        rtIsoPabel1 = rtIsoSliderPanel;
        currentMinRTIsoText = new javax.swing.JLabel();
        q1Check = new javax.swing.JCheckBox();
        q2Check = new javax.swing.JCheckBox();
        q4Check = new javax.swing.JCheckBox();
        q3Check = new javax.swing.JCheckBox();

        jLabel24.setText("Alpha:");

        preIsoAlphaText.setText("1.0");

        preIsoAddButton.setText("Add");
        preIsoAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preIsoAddButtonActionPerformed(evt);
            }
        });

        preIsoList.setModel(isoSurfaces);
        jScrollPane3.setViewportView(preIsoList);

        preIsoShowButton.setText("Show");
        preIsoShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preIsoShowButtonActionPerformed(evt);
            }
        });

        preIsoHideButton.setText("Hide");
        preIsoHideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preIsoHideButtonActionPerformed(evt);
            }
        });

        preIsoDelButton.setText("Del");
        preIsoDelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preIsoDelButtonActionPerformed(evt);
            }
        });

        jLabel25.setText("steps:");

        preIsoSteps.setText("1");

        setPreIsoButton.setText("S");
        setPreIsoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPreIsoButtonActionPerformed(evt);
            }
        });

        saveIsoButton.setText("Save");
        saveIsoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveIsoButtonActionPerformed(evt);
            }
        });

        minRTIsoText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minRTIsoText.setText("0");
        minRTIsoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRTIsoTextActionPerformed(evt);
            }
        });

        maxRTIsoText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxRTIsoText.setText("2000");

        rtIsoPabel1.setBackground(new java.awt.Color(255, 255, 255));
        rtIsoPabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rtIsoPabel1MouseDragged(evt);
            }
        });
        rtIsoPabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rtIsoPabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rtIsoPabel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout rtIsoPabel1Layout = new javax.swing.GroupLayout(rtIsoPabel1);
        rtIsoPabel1.setLayout(rtIsoPabel1Layout);
        rtIsoPabel1Layout.setHorizontalGroup(
            rtIsoPabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        rtIsoPabel1Layout.setVerticalGroup(
            rtIsoPabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        currentMinRTIsoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentMinRTIsoText.setText("1000");

        q1Check.setSelected(true);
        q1Check.setText("1");

        q2Check.setSelected(true);
        q2Check.setText("2");

        q4Check.setSelected(true);
        q4Check.setText("4");

        q3Check.setSelected(true);
        q3Check.setText("3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preIsoProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(preIsoDelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveIsoButton))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(preIsoHideButton)
                                    .addComponent(preIsoShowButton))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(preIsoAlphaText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(setPreIsoButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preIsoSteps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preIsoAddButton))
                    .addComponent(rtIsoPabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(minRTIsoText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maxRTIsoText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(currentMinRTIsoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q1Check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q2Check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q3Check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q4Check)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minRTIsoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRTIsoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtIsoPabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentMinRTIsoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1Check)
                    .addComponent(q2Check)
                    .addComponent(q3Check)
                    .addComponent(q4Check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(preIsoSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preIsoAddButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preIsoProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(preIsoShowButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preIsoHideButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preIsoAlphaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setPreIsoButton)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preIsoDelButton)
                    .addComponent(saveIsoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public int getIsoStep() {
        return Parse.stringToInt( preIsoSteps.getText() );
    }

    public void updateIsoProgress(int p) {
        preIsoProgress.setValue( p );
    }

    public void addIsoSurface(IsoSurface iSurface) {
        isoSurfaces.add(iSurface);
        preIsoAddButton.setEnabled(true);
        mf.needUpdate();
    }
    
    private void preIsoAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preIsoAddButtonActionPerformed
        preIsoAddButton.setEnabled(false);
        
        MarchingCubes mc = new MarchingCubes(this, getRtMinIsoValue(), null);
        mc.start();
    }//GEN-LAST:event_preIsoAddButtonActionPerformed

    public void calcIsoSurface(ActionListener listener){
        preIsoAddButton.setEnabled(false);
        MarchingCubes mc = new MarchingCubes(this, getRtMinIsoValue(), listener);
        mc.start();
    }
    
    public float getRtMinIsoValue() {
        return Parse.stringToFloat( currentMinRTIsoText.getText() );
    }
    
    private void preIsoShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preIsoShowButtonActionPerformed
        int[] s = preIsoList.getSelectedIndices();
        for(int is : s){
            isoSurfaces.getAt(is).setVisible(true);
        }
        isoSurfaces.updateAll();
        mf.needUpdate();
    }//GEN-LAST:event_preIsoShowButtonActionPerformed

    private void preIsoHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preIsoHideButtonActionPerformed
        int[] s = preIsoList.getSelectedIndices();
        for(int is : s){
            isoSurfaces.getAt(is).setVisible(false);
        }
        isoSurfaces.updateAll();
        mf.needUpdate();
    }//GEN-LAST:event_preIsoHideButtonActionPerformed

    
    public void clearIsoSurfaces(){
        for(IsoSurface is : isoSurfaces.getElements()){
            is.removeFromScene(mf.scene);
        }
        isoSurfaces.clear();
    }
    
    private void preIsoDelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preIsoDelButtonActionPerformed
        int[] s = preIsoList.getSelectedIndices();
        for(int is : s){
            isoSurfaces.getAt(is).removeFromScene(mf.scene);
        }
        isoSurfaces.delete(s);
        mf.needUpdate();
    }//GEN-LAST:event_preIsoDelButtonActionPerformed

    private void setPreIsoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPreIsoButtonActionPerformed
        int[] s = preIsoList.getSelectedIndices();
        float alpha = Parse.stringToFloat(preIsoAlphaText.getText());
        for(int is : s){
            isoSurfaces.getAt(is).setAlpha(alpha);
        }
        isoSurfaces.updateAll();
        mf.needUpdate();
    }//GEN-LAST:event_setPreIsoButtonActionPerformed

    private void saveIsoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveIsoButtonActionPerformed
        String path = FileUtils.selectDirectory(this, "select", null);
        if(path != null){
            int[] s = preIsoList.getSelectedIndices();
            for(int i : s){
                IsoSurface iso =  isoSurfaces.getAt(i);
                iso.saveToFile( path + "/" + iso.toString() + ".obj");
            }
        }
    }//GEN-LAST:event_saveIsoButtonActionPerformed

    private void minRTIsoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRTIsoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minRTIsoTextActionPerformed

    public boolean isQ1(){
        return q1Check.isSelected();
    }
    public boolean isQ2(){
        return q2Check.isSelected();
    }
    public boolean isQ3(){
        return q3Check.isSelected();
    }
    public boolean isQ4(){
        return q4Check.isSelected();
    }

    
    private void rtIsoPabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rtIsoPabel1MouseDragged
        rtIsoSliderPanel.touchDrag(evt.getX(), evt.getY());
        float min = Parse.stringToFloat( minRTIsoText.getText() );
        float max = Parse.stringToFloat( maxRTIsoText.getText() );
        float current = min + (max-min) * rtIsoSliderPanel.getCurrent();
        if ( rtIsoSliderPanel.getLastButton() == 0){
            currentMinRTIsoText.setText( mf.decimalFormat2.format(current) );
        }
        mf.needUpdate();
    }//GEN-LAST:event_rtIsoPabel1MouseDragged

    private void rtIsoPabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rtIsoPabel1MousePressed

        rtIsoSliderPanel.touchDown(evt.getX(), evt.getY(), evt.getButton() == 1 ? 0 : 1);
        rtIsoPabel1MouseDragged(evt);
    }//GEN-LAST:event_rtIsoPabel1MousePressed

    private void rtIsoPabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rtIsoPabel1MouseReleased

    }//GEN-LAST:event_rtIsoPabel1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentMinRTIsoText;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maxRTIsoText;
    private javax.swing.JTextField minRTIsoText;
    private javax.swing.JButton preIsoAddButton;
    private javax.swing.JTextField preIsoAlphaText;
    private javax.swing.JButton preIsoDelButton;
    private javax.swing.JButton preIsoHideButton;
    private javax.swing.JList preIsoList;
    private javax.swing.JProgressBar preIsoProgress;
    private javax.swing.JButton preIsoShowButton;
    private javax.swing.JTextField preIsoSteps;
    private javax.swing.JCheckBox q1Check;
    private javax.swing.JCheckBox q2Check;
    private javax.swing.JCheckBox q3Check;
    private javax.swing.JCheckBox q4Check;
    private javax.swing.JPanel rtIsoPabel1;
    private javax.swing.JButton saveIsoButton;
    private javax.swing.JButton setPreIsoButton;
    // End of variables declaration//GEN-END:variables
}
