/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package acousticfield3d.gui.panels;

import acousticfield3d.gui.MainForm;
import acousticfield3d.gui.controls.VolAlphaPanel;
import acousticfield3d.renderer.VolRTShader;
import acousticfield3d.scene.Entity;
import acousticfield3d.scene.Resources;
import acousticfield3d.scene.Scene;
import acousticfield3d.utils.Parse;

/**
 *
 * @author Asier
 */
public class RtVolPanel extends javax.swing.JPanel {
    public MainForm mf;
    
    VolAlphaPanel volRTAlphaPanel;
    
    public RtVolPanel(MainForm mf) {
        this.mf = mf;
        volRTAlphaPanel = new VolAlphaPanel(VolRTShader.ALPHA_MAP_VALUES);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alphaVolRTPanel = volRTAlphaPanel;
        jLabel26 = new javax.swing.JLabel();
        rtVolAmpGainText = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        rtVolDensityText = new javax.swing.JTextField();
        rtVolAlphaText = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        rtVolEnableCheck = new javax.swing.JCheckBox();
        simTortCubeButton = new javax.swing.JButton();
        rtCubeToSimButton = new javax.swing.JButton();
        calcRtVolCheck = new javax.swing.JCheckBox();

        alphaVolRTPanel.setBackground(new java.awt.Color(255, 255, 255));
        alphaVolRTPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                alphaVolRTPanelMouseDragged(evt);
            }
        });
        alphaVolRTPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                alphaVolRTPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout alphaVolRTPanelLayout = new javax.swing.GroupLayout(alphaVolRTPanel);
        alphaVolRTPanel.setLayout(alphaVolRTPanelLayout);
        alphaVolRTPanelLayout.setHorizontalGroup(
            alphaVolRTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        alphaVolRTPanelLayout.setVerticalGroup(
            alphaVolRTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        jLabel26.setText("AmpS:");

        rtVolAmpGainText.setText("1500");
        rtVolAmpGainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtVolAmpGainTextActionPerformed(evt);
            }
        });

        jLabel27.setText("Density:");

        rtVolDensityText.setText("128");

        rtVolAlphaText.setText("0.8");

        jLabel28.setText("Alpha:");

        rtVolEnableCheck.setText("Enable");
        rtVolEnableCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtVolEnableCheckActionPerformed(evt);
            }
        });

        simTortCubeButton.setText("c=s");
        simTortCubeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simTortCubeButtonActionPerformed(evt);
            }
        });

        rtCubeToSimButton.setText("s=c");
        rtCubeToSimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtCubeToSimButtonActionPerformed(evt);
            }
        });

        calcRtVolCheck.setSelected(true);
        calcRtVolCheck.setText("calc");
        calcRtVolCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcRtVolCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alphaVolRTPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtVolEnableCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simTortCubeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtCubeToSimButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calcRtVolCheck)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rtVolAlphaText))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rtVolAmpGainText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rtVolDensityText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alphaVolRTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rtVolAmpGainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(rtVolDensityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(rtVolAlphaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(simTortCubeButton)
                        .addComponent(rtCubeToSimButton))
                    .addComponent(rtVolEnableCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcRtVolCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alphaVolRTPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alphaVolRTPanelMouseDragged
        volRTAlphaPanel.setValueAt(evt.getX(), evt.getY());
    }//GEN-LAST:event_alphaVolRTPanelMouseDragged

    private void alphaVolRTPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alphaVolRTPanelMousePressed
        volRTAlphaPanel.setValueAt(evt.getX(), evt.getY());
    }//GEN-LAST:event_alphaVolRTPanelMousePressed

    private void rtVolAmpGainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtVolAmpGainTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtVolAmpGainTextActionPerformed

    private void rtVolEnableCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtVolEnableCheckActionPerformed
        Scene.setVisible(mf.scene.getEntities(), Entity.TAG_RT_VOL, rtVolEnableCheck.isSelected());
        mf.needUpdate();
    }//GEN-LAST:event_rtVolEnableCheckActionPerformed

    private void simTortCubeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simTortCubeButtonActionPerformed
        mf.scene.simToCube(mf.scene.getRtCubeVol(), mf.simulation );
        mf.needUpdate();
    }//GEN-LAST:event_simTortCubeButtonActionPerformed

    private void rtCubeToSimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtCubeToSimButtonActionPerformed
        mf.scene.cubeToSim( mf.scene.getRtCubeVol(), mf.simulation);
        mf.scene.updateBoundaryBoxes(mf.simulation);
        mf.needUpdate();
    }//GEN-LAST:event_rtCubeToSimButtonActionPerformed

    private void calcRtVolCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcRtVolCheckActionPerformed
        Scene.setShader(mf.scene.getEntities(), Entity.TAG_RT_VOL,
            calcRtVolCheck.isSelected() ? Resources.SHADER_VOL_RT : Resources.SHADER_SOLID_SPEC);
        mf.needUpdate();
    }//GEN-LAST:event_calcRtVolCheckActionPerformed


    public VolAlphaPanel getRTVolAlphaPanel() {
        return volRTAlphaPanel;
    }

    public float getRTCubeMaxAlpha() {
        return Parse.stringToFloat( rtVolAlphaText.getText());
    }

    public float getRTVolDensity() {
        return Parse.stringToFloat( rtVolDensityText.getText() );
    }

    public float getRTVolAmpScale() {
        return Parse.stringToFloat( rtVolAmpGainText.getText());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alphaVolRTPanel;
    private javax.swing.JCheckBox calcRtVolCheck;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JButton rtCubeToSimButton;
    private javax.swing.JTextField rtVolAlphaText;
    private javax.swing.JTextField rtVolAmpGainText;
    private javax.swing.JTextField rtVolDensityText;
    private javax.swing.JCheckBox rtVolEnableCheck;
    private javax.swing.JButton simTortCubeButton;
    // End of variables declaration//GEN-END:variables
}
