/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package acousticfield3d.gui.controls;

import acousticfield3d.gui.panels.MovePanel;
import acousticfield3d.math.FastMath;
import acousticfield3d.math.Transform;
import acousticfield3d.math.Vector3f;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

/**
 *
 * @author Asier
 */
public class ScriptEditFrame extends javax.swing.JFrame {
    MovePanel father;
    ScriptEngineManager manager;
    ScriptEngine engine;
    
    public ScriptEditFrame(MovePanel father) {
        this.father = father;
        initComponents();
        try{
            manager = new ScriptEngineManager();
            engine = manager.getEngineByName("js");
            engine.put("math", new FastMath());
            engine.put("trans", new Transform());
            okButtonActionPerformed( null );
        }catch(Exception ex){
            Logger.getLogger(ScriptEditFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();
        errorText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Move script");

        area.setColumns(20);
        area.setRows(5);
        area.setTabSize(4);
        area.setText("//diagonal\nfunction calc(){\n\tvar a = math.sin(t * math.PI * 2.0);\n\tv.x = a;\n\tv.y = a;\n\tv.z = a;\n}\n\n//rose\n/*\nfunction calc(){\n\tvar k = 6.0/4.0;\n\tvar s = t * math.PI * 2.0;\n\tvar cosKS = math.cos(k*s);\n\t\n\tv.x = cosKS * math.cos(s);\n\tv.y = 0;\n\tv.z = cosKS * math.sin(s);\n}\n*/\n\n//lissajous\n/*\nfunction calc(){\n\tvar s = t * math.PI * 2.0;\n\t\n\tv.x = math.cos(s * 3.0);\n\tv.y = math.sin(s * 7.0);\n\tv.z = math.sin(s * 2.0);\n}\n*/\n\n//superhelix\n/*\nfunction calc(){\n\t\n\tvar t1 = trans.create();\n\tvar t2 = trans.create();\n\tvar t3 = trans.create();\n\t\n\tt1.translation.y = 0.4;\n\tt2.rotation.rotate(0,0, t*30);\n\tt2.translation.x = 0.6;\n\tt3.rotation.rotate(0, t, 0);\n\t\n\tt1.combineWithParent(t2);\n\tt1.combineWithParent(t3);\n\t\n\tt1.transformPoint(v,v);\n}\n*/");
        jScrollPane1.setViewportView(area);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(errorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(engine != null){
            try {
                engine.put("calc", null);
                engine.eval( area.getText() );
                errorText.setText("OK :)");
            } catch (ScriptException ex) {
                errorText.setText( ex.getLineNumber() + ":" + ex.getColumnNumber() + " " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    public Vector3f evalScript(float t) throws ScriptException{
        Vector3f v = new Vector3f();
        if (engine != null){
                engine.put("t", t);
                engine.put("v", v);
                engine.eval("calc()");
        }
        return v;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField errorText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
