/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package acousticfield3d.gui;

import acousticfield3d.math.Matrix4f;

/**
 *
 * @author Asier
 */
public class ProjectionForm extends javax.swing.JFrame {
    Matrix4f projection;
    
    public ProjectionForm(Matrix4f projection) {
        this.projection = projection;
        initComponents();
        projectionToArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fovText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        aspectText = new javax.swing.JTextField();
        orthoCheck = new javax.swing.JCheckBox();
        fovSetButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        matrixArea = new javax.swing.JTextArea();
        matrixSetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nearText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        farText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("FOV:");

        fovText.setText("45");

        jLabel2.setText("aspect:");

        aspectText.setText("1.5");

        orthoCheck.setText("Ortho");

        fovSetButton.setText("Set");
        fovSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fovSetButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Matrix");

        matrixArea.setColumns(20);
        matrixArea.setRows(5);
        jScrollPane1.setViewportView(matrixArea);

        matrixSetButton.setText("Set");
        matrixSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrixSetButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Near:");

        nearText.setText("0.001");

        jLabel5.setText("Far:");

        farText.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrixSetButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nearText))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fovText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aspectText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(orthoCheck))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(farText)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fovSetButton)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fovText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(aspectText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orthoCheck)
                    .addComponent(fovSetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(farText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(matrixSetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void fovSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fovSetButtonActionPerformed
        final float fov = Float.parseFloat( fovText.getText() );
        final float aspect = Float.parseFloat( aspectText.getText() );
        final boolean ortho = orthoCheck.isSelected();
        final float near = Float.parseFloat( nearText.getText() );
        final float far = Float.parseFloat( farText.getText() );
        
        if (ortho){
            projection.setProjection(near, far, -aspect, aspect, -1, 1, true);
        }else{
            projection.setProjectionFOV(fov, near, far, aspect);
        }
        projectionToArea();
    }//GEN-LAST:event_fovSetButtonActionPerformed

    private void matrixSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixSetButtonActionPerformed
        projection.parse( matrixArea.getText() );
        projectionToArea();
    }//GEN-LAST:event_matrixSetButtonActionPerformed

    private void projectionToArea(){
        matrixArea.setText( projection.toString() );
    }
    
    public static void main(String[] args){
        ProjectionForm pf = new ProjectionForm(new Matrix4f());
        pf.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aspectText;
    private javax.swing.JTextField farText;
    private javax.swing.JButton fovSetButton;
    private javax.swing.JTextField fovText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea matrixArea;
    private javax.swing.JButton matrixSetButton;
    private javax.swing.JTextField nearText;
    private javax.swing.JCheckBox orthoCheck;
    // End of variables declaration//GEN-END:variables
}
