/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package acousticfield3d.gui;

import acousticfield3d.math.Vector3f;
import acousticfield3d.scene.Entity;

/**
 *
 * @author Asier
 */
public class ReportFrame extends javax.swing.JFrame {
    MainForm mf;
    Entity lockedEntity;
    
    /**
     * Creates new form ReportFrame
     */
    public ReportFrame(MainForm mf) {
        this.mf = mf;
        initComponents();
    }

    public void addLine(String l){
        area.append( l );
    }
    
    public Vector3f getPosition(){
        return new Vector3f().parse( posText.getText() );
    }
    
    public void setPosition(Vector3f v){
        posText.setText( v.toStringSimple() );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        posText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();
        snapPositionButton = new javax.swing.JButton();
        lockEntityButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Report Frame");

        jLabel1.setText("position:");

        posText.setText("0.0 0.0 0.0");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        snapPositionButton.setText("Snap");
        snapPositionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapPositionButtonActionPerformed(evt);
            }
        });

        lockEntityButton.setText("LockEntity");
        lockEntityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockEntityButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(snapPositionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lockEntityButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(posText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snapPositionButton)
                    .addComponent(lockEntityButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void snapPositionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snapPositionButtonActionPerformed
        //get selected object
        if ( mf.getSelection().isEmpty() ){
            return;
        }
        final Entity selectedObject = mf.getSelection().get(0);
        posText.setText( selectedObject.getTransform().getTranslation().toStringSimple() );
    }//GEN-LAST:event_snapPositionButtonActionPerformed

    private void lockEntityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockEntityButtonActionPerformed
        //get selected object
        if ( mf.getSelection().isEmpty() ){
            return;
        }
        final Entity selectedObject = mf.getSelection().get(0);
        lockedEntity = selectedObject;
    }//GEN-LAST:event_lockEntityButtonActionPerformed

    public Entity getLockedEntity() {
        return lockedEntity;
    }

    public void setLockedEntity(Entity lockedEntity) {
        this.lockedEntity = lockedEntity;
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lockEntityButton;
    private javax.swing.JTextField posText;
    private javax.swing.JButton snapPositionButton;
    // End of variables declaration//GEN-END:variables
}
