/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package acousticfield3d.gui;

import acousticfield3d.math.FastMath;
import acousticfield3d.simulation.Transducer;

/**
 *
 * @author Asier
 */
public class TransducersOffsetForm extends javax.swing.JFrame {
    MainForm mf;
    
    public TransducersOffsetForm(MainForm mf) {
        this.mf = mf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distributionGroup = new javax.swing.ButtonGroup();
        ampCheck = new javax.swing.JCheckBox();
        phaseCheck = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        ampAvgText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ampStdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phaseAvgText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phaseStdText = new javax.swing.JTextField();
        setButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        xCheck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        xAvgText = new javax.swing.JTextField();
        xStdText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        xSText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        yStdText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        yAvgText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ySText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        yCheck = new javax.swing.JCheckBox();
        zStdText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        zAvgText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        zSText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        zCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transducers Offset");

        ampCheck.setText("Amplitude(0-1)");

        phaseCheck.setText("Phase(Pi)");

        jLabel1.setText("Avg:");

        ampAvgText.setText("0.00");

        jLabel2.setText("Std:");

        ampStdText.setText("0.01");

        jLabel3.setText("Avg:");

        phaseAvgText.setText("0.00");

        jLabel4.setText("Std:");

        phaseStdText.setText("0.01");

        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        xCheck.setText("X");

        jLabel5.setText("Avg:");

        xAvgText.setText("0.00");

        xStdText.setText("0.01");

        jLabel6.setText("Std:");

        xSText.setText("1.00");

        jLabel7.setText("S:");

        yStdText.setText("0.01");

        jLabel8.setText("Std:");

        yAvgText.setText("0.00");

        jLabel9.setText("Avg:");

        ySText.setText("1.00");

        jLabel10.setText("S:");

        yCheck.setText("Y");

        zStdText.setText("0.01");

        jLabel11.setText("Std:");

        zAvgText.setText("0.00");

        jLabel12.setText("Avg:");

        zSText.setText("1.00");

        jLabel13.setText("S:");

        zCheck.setText("Z");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zSText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zStdText, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ampCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(phaseCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ampAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phaseAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xSText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(xStdText, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(phaseStdText)
                            .addComponent(ampStdText)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ySText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yStdText, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ampCheck)
                    .addComponent(jLabel1)
                    .addComponent(ampAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ampStdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phaseCheck)
                    .addComponent(jLabel3)
                    .addComponent(phaseAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(phaseStdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xCheck)
                    .addComponent(jLabel5)
                    .addComponent(xAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(xStdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xSText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yCheck)
                    .addComponent(jLabel9)
                    .addComponent(yAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(yStdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ySText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zCheck)
                    .addComponent(jLabel12)
                    .addComponent(zAvgText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(zStdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zSText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setButton)
                    .addComponent(clearButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        boolean amp = ampCheck.isSelected();
        boolean phase = phaseCheck.isSelected();
        boolean x = xCheck.isSelected();
        boolean y = yCheck.isSelected();
        boolean z = zCheck.isSelected();
        float ampAvg = Float.parseFloat( ampAvgText.getText() );
        float ampStd = Float.parseFloat( ampAvgText.getText() );
        float phaseAvg = Float.parseFloat( phaseAvgText.getText() );
        float phaseStd = Float.parseFloat( phaseStdText.getText() );
        
        float xS = Float.parseFloat( xSText.getText() );
        float xAvg = Float.parseFloat( xAvgText.getText() );
        float xStd = Float.parseFloat( xStdText.getText() );
        float yS = Float.parseFloat( ySText.getText() );
        float yAvg = Float.parseFloat( yAvgText.getText() );
        float yStd = Float.parseFloat( yStdText.getText() );
        float zS = Float.parseFloat( zSText.getText() );
        float zAvg = Float.parseFloat( zAvgText.getText() );
        float zStd = Float.parseFloat( zStdText.getText() );
        
        for( Transducer t : mf.simulation.getTransducers() ){
            if ( amp) { t.setpAmplitudeOffset( FastMath.randomGaussian(ampAvg, ampStd) ); }
            if (phase) { t.setPhaseOffset( FastMath.randomGaussian(phaseAvg, phaseStd) ); }
            if(x){
                t.getTransform().getTranslation().x *= xS;
                t.getTransform().getTranslation().x +=  FastMath.randomGaussian(xAvg, xStd) ;
            }
            if(y){
                t.getTransform().getTranslation().y *= yS;
                t.getTransform().getTranslation().y +=  FastMath.randomGaussian(yAvg, yStd) ;
            }
            if(z){
                t.getTransform().getTranslation().z *= zS;
                t.getTransform().getTranslation().z +=  FastMath.randomGaussian(zAvg, zStd) ;
            }
        }
        mf.needUpdate();
    }//GEN-LAST:event_setButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        for( Transducer t : mf.simulation.getTransducers() ){
            t.setpAmplitudeOffset( 0 );
            t.setPhaseOffset( 0 );
        }
        mf.needUpdate();
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ampAvgText;
    private javax.swing.JCheckBox ampCheck;
    private javax.swing.JTextField ampStdText;
    private javax.swing.JButton clearButton;
    private javax.swing.ButtonGroup distributionGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField phaseAvgText;
    private javax.swing.JCheckBox phaseCheck;
    private javax.swing.JTextField phaseStdText;
    private javax.swing.JButton setButton;
    private javax.swing.JTextField xAvgText;
    private javax.swing.JCheckBox xCheck;
    private javax.swing.JTextField xSText;
    private javax.swing.JTextField xStdText;
    private javax.swing.JTextField yAvgText;
    private javax.swing.JCheckBox yCheck;
    private javax.swing.JTextField ySText;
    private javax.swing.JTextField yStdText;
    private javax.swing.JTextField zAvgText;
    private javax.swing.JCheckBox zCheck;
    private javax.swing.JTextField zSText;
    private javax.swing.JTextField zStdText;
    // End of variables declaration//GEN-END:variables
}
